services:
  db:
    image: postgres:16
    container_name: iris-data
    restart: always
    ports:
      - "5343:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - iris_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./api
    environment:
      DB_HOST: db
      DATABASE_URL: "postgresql://user:password@db:5432/mydb?schema=public"
      PORT: 3000
      JWT_SECRET: "seu-jwt-secret-aqui"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - iris_network
    command: >
      sh -c "sleep 10 && pnpm prisma migrate deploy && pnpm start:prod"

  front:
    build:
      context: ./front
    environment:
      - VITE_API_URL=http://app:3000
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - iris_network
    restart: always

volumes:
  postgres-data:
networks:
  iris_network:
    driver: bridge  