version: '3.8'

services:
  db:
    image: postgres:16
    container_name: iris-data
    restart: always
    ports:
      - "5343:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - iris_network
      
volumes:
  postgres-data:
networks:
  iris_network:
    driver: bridge  