export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY'
export const CLIENTE_REPOSITORY = 'CLIENTE_REPOSITORY'
export const CORES_REPOSITORY = 'CORES_REPOSITORY'

export const AUTH_SERVICE = 'AUTH_SERVICE'
export const USUARIO_SERVICE = 'USUARIO_SERVICE'
export const CLIENTE_SERVICE = 'CLIENTE_SERVICE'
export const CORES_SERVICE = 'CORES_SERVICE'

export const APP_GUARD = 'APP_GUARD'
